apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ghlf48m-f-nodejs 
  janus-idp.io/tekton: ghlf48m-f-nodejs
  backstage.io/kubernetes-id: ghlf48m-f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ghlf48m-f-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  