apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ghlf48m-f-nodejs-gitops
  description: This is GitOps manifest for ghlf48m-f-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ghlf48m-f-nodejs
    janus-idp.io/tekton: ghlf48m-f-nodejs 
    backstage.io/kubernetes-id: ghlf48m-f-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ghlf48m-f-nodejs
